# fly.toml app configuration file generated for review-deez-backend on 2023-08-25T00:40:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "review-deez-backend"
primary_region = "cdg"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
